#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2010-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import fontforge
import sys

for filename in sys.argv[1:]:
    font = fontforge.open(filename)
    print('{0}: {1}'.format(filename, font.copyright))

# vim:ts=4 sw=4 et
