#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2010-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import argparse
import sys

import fontforge

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('paths', metavar='FILE', nargs='+')
    options = ap.parse_args()
    for filename in options.paths:
        font = fontforge.open(filename)
        copyright = font.copyright
        copyright = copyright.replace('\n', '\t')
        print('{0}: {1}'.format(filename, copyright))

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
