#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2010-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import fontforge

0_0  # Python >= 3.6 is required

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('paths', metavar='FILE', nargs='+')
    options = ap.parse_args()
    for path in options.paths:
        font = fontforge.open(path)
        copyright = font.copyright
        copyright = copyright.replace('\n', '\t')
        copyright = copyright.strip()
        print(f'{path}: {copyright}')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
