name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install FontForge Python bindings
      run:
        sudo apt-get install python3-fontforge
    - name: smoke test (#1)
      run:
        ./fontcoprinfo --help
    - name: smoke test (#2)
      run:
        ./fontcoprinfo /usr/share/fonts/truetype/*/*Serif*.ttf 2>/dev/null
    - name: run pydiatra
      run: |
        python3 -m pip install --user pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install --user pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install --user restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
